CREATE TABLE IF NOT EXISTS "Profile"."MentorTimes" (
	"TimeId" BIGSERIAL,
	"TimeStart" TIME NOT NULL,
	"TimeEnd" TIME NOT NULL,
	"DayId" INT4 NOT NULL DEFAULT 1,
	"UserId" BIGINT NOT NULL,
	CONSTRAINT "PK_MentorTimesTimeId" PRIMARY KEY ("TimeId")
);